# Generated by Django 5.2.7 on 2025-10-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_fooditem_image_fooditem_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
