# Generated by Django 5.2.7 on 2025-10-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_fooditem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
