# Generated by Django 5.2.7 on 2025-10-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_fooditem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Card Payment', 'Card Payment'), ('UPI', 'UPI')], default='Cash on Delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
